projects/2020/x/wiki/encyclopedia/urls.py
from django.urls import path

from . import views
app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("newEntry", views.newPage, name= "newPage"),
    path("wiki/<str:entry>", views.entry, name="entry"),
    path("randomPage/", views.randomPage, name="randomPage"),
    path("edit/<str:entry>", views.editPage, name="editPage"),
    path("search", views.search, name="search"),
    ]

projects/2020/x/wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

projects/2020/x/wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

projects/2020/x/wiki/encyclopedia/views.py
from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponseRedirect
from django import forms
from django.shortcuts import redirect
import re
import random
from . import util

def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })
def markDown2Html(entry):
    html = util.get_entry(entry)
    #headings
    # Handle headings
    html = re.sub(r'^(#+)\s*(.+)', lambda match: f'<h{len(match.group(1))}>{match.group(2)}</h{len(match.group(1))}>', html, flags=re.MULTILINE)
    #bold
    html = re.sub(r'\*\*(.*?)\*\*', r'<strong>\1</strong>', html)
    #unordered list
    html = re.sub(r'^\* *(.+)', r'<ul><li>\1</li></ul>', html, flags=re.MULTILINE)
    #link
    html = re.sub(r'\[(.+?)\]\((.+?)\)', r'<a href="\2">\1</a>', html)
    #paragraph
    html = re.sub(r'^([^<\n].+)$', r'<p>\1</p>', html, flags=re.MULTILINE)
    return html

def entry(request, entry):
    if util.get_entry(entry):
        html= markDown2Html(entry)
        title_match = re.search(r'^#\s*(.+)', util.get_entry(entry), re.MULTILINE)
        if title_match:
            title = title_match.group(1)
        else:
            title = "Untitled"  # Default title if no heading is found
        return render(request, "encyclopedia/entry.html", {"entry": html, "title": title})
    else:
        return render(request, "encyclopedia/error.html")

class NewEntryForm(forms.Form):
    title = forms.CharField(label="Title of New Entry", widget=forms.TextInput(attrs={"class": "form-control"}))
    content = forms.CharField(label="Content", widget=forms.Textarea(attrs={"class": "form-control"}))

    def is_valid(self):
        valid = super().is_valid()
        if valid:
            title = self.cleaned_data.get('title')
            content = self.cleaned_data.get('content')
            title_match = (re.search(r'^#\s*(.+)', content, re.MULTILINE))
            print(title)
            print(title_match)
            if not re.search(r'^#\s+.+', content, re.MULTILINE):
                self.add_error('content', 'The content must start with a Markdown heading (# ) and additional whitespace')
                return False
            if title.strip() != title_match.group(1).strip():
                self.add_error('content', 'The title in the title part and markdown part should match!')
                return False
        return valid


def newPage(request):
    if request.method == "POST":
        form = NewEntryForm(request.POST)
        if form.is_valid():
            if form.cleaned_data['title'] in util.list_entries():
                form.add_error('title', 'This title already exists.')
                return render(request, "encyclopedia/newPage.html", {
                "form": form
                })            
            else:
                title = form.cleaned_data['title']
                content = form.cleaned_data['content']
                util.save_entry(title, content)
                return HttpResponseRedirect(reverse("encyclopedia:entry", args=[title]))
        else:
            return render(request, "encyclopedia/newPage.html", {
                "form": form
                })
    else:
        return render(request, "encyclopedia/newPage.html", {
            "form": NewEntryForm()
        })

def randomPage(request):
    entries = util.list_entries()
    random_entry = random.choice(entries)
    return HttpResponseRedirect(reverse("encyclopedia:entry", args=(random_entry,)))

class editEntryForm(forms.Form):
    content = forms.CharField(label="",widget=forms.Textarea(attrs={"class":"form-control"}))

    def clean_content(self):
        content = self.cleaned_data['content'].strip()
        return content



def editPage(request, entry):
    entry = entry.strip()
    if request.method == "POST":
        form = editEntryForm(request.POST)
        if form.is_valid():
            content = form.cleaned_data['content'].strip()
            util.save_entry(entry, content)
            return HttpResponseRedirect(reverse("encyclopedia:entry", args=[entry]))
    else:
        content = util.get_entry(entry)
        form = editEntryForm(initial={'content': content})
    
    return render(request, "encyclopedia/editPage.html", {
        "form": form,
        "entry": entry
    })

def search(request):
    query = request.GET.get('q', '')
    entries = util.list_entries()
    results = [entry for entry in entries if query.lower() in entry.lower()]
    
    if query.lower() in [entry.lower() for entry in entries]:
        return HttpResponseRedirect(reverse("encyclopedia:entry", args=[query]))
    
    return render(request, "encyclopedia/search.html", {
        "entries": results,
    })

projects/2020/x/wiki/encyclopedia/templates/encyclopedia/editPage.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia - Add New Entry
{% endblock %}

{% block body %}
    <h1>Edit Entry</h1>
    
    <form action="{% url 'encyclopedia:editPage' entry=entry %}" method="post">
        {% csrf_token %}
        {{ form.content }}
        <input type="submit" class="btn btn-primary" value="Save Entry">
    </form>    
    
{% endblock %}

projects/2020/x/wiki/encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{title}}
{% endblock %}

{% block body %}
    <div class="content">
        {{ entry|safe }}
    </div>
    <div>
        <a href="{% url 'encyclopedia:editPage' entry=title %}" class="btn btn-primary">Edit</a>
    </div>
{% endblock %}

projects/2020/x/wiki/encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Page Not Found
{% endblock %}

{% block body %}
    <h1>Page Not Found</h1>
    <p>The requested page was not found.</p>
{% endblock %}

projects/2020/x/wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
        <a href="{% url 'encyclopedia:entry' entry=entry %}"><li>{{ entry }}</li></a>
        {% endfor %}
    </ul>

{% endblock %}

projects/2020/x/wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
</head>
<body>
    <div class="row">
        <div class="sidebar col-lg-2 col-md-3">
            <h2>Wiki</h2>
            <form method="GET" action="{% url 'encyclopedia:search' %}">
                <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
            </form>
            <div>
                <a href="{% url 'encyclopedia:index' %}">Home</a>
            </div>
            <div>
                <a href="{% url 'encyclopedia:newPage'%}">New Page</a>
            </div>
            <div>
                <a href="{% url 'encyclopedia:randomPage' %}">Random Page</a>
            </div>
            {% block nav %}
            {% endblock %}
        </div>
        <div class="main col-lg-10 col-md-9">
            {% block body %}
            {% endblock %}
        </div>
    </div>
</body>
</html>

projects/2020/x/wiki/encyclopedia/templates/encyclopedia/newPage.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia - Add New Entry
{% endblock %}

{% block body %}
    <h1>Add New Entry</h1>
    
    <form action="{% url 'encyclopedia:newPage' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Save Entry">
    </form>
{% endblock %}

projects/2020/x/wiki/encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia - Search Results
{% endblock %}

{% block body %}
    <h1>Search Results</h1>
    
    {% if entries %}
        <ul>
        {% for entry in entries %}
            <li><a href="{% url 'encyclopedia:entry' entry=entry %}">{{ entry }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No results found.</p>
    {% endif %}
    
{% endblock %}